
/* USing the data from Datawarehouse project we have done Data Analytics 
===============================================

*/


use datawarehouse


-- in case we want to check all tables in database 
select * from information_schema.TABLES


-- in case we want to explore all columns in database	
select	* from	information_schema.COLUMNS

-- in case we want to explore columns of a particular table 

select	* from	information_schema.COLUMNS
where table_name = 'dim_customers'

-- explore all countries or=ur customers come from

select distinct cntry from gold.dim_customers

-- explorre all categories 'the major divisions'

select distinct category, subcategory from gold.dim_products

-- explore date and their range

	select 
	Min(order_date) first_order_date,
	Max(order_date) last_order_date,
	DATEDIFF(YEAR, min(order_date), Max(order_date))
	from gold.fact_sales

-- find youngest and oldest customer 

select 
min(birth_date) oldest_customer,
max(birth_date) youngest_customer,
datediff(year, min(birth_date), max(birth_date)) customer_age_gap
from gold.dim_customers

-- finding age of customer
select 
min(birth_date) oldest_customer,
max(birth_date) youngest_customer,
datediff(year, min(birth_date), getdate()) youngest_customer_age,
datediff(year, max(birth_date), getdate()) oldest_customer_age
from gold.dim_customers


-- Aggregation Measures

-- Find total sales
select 
Sum(sales_amount) total_sales
from gold.fact_sales


-- find how many items are sold
select 
sum(quantity) total_items 
from gold.fact_sales

-- find the average selling price

select 
avg(price) avg_price
from gold.fact_sales

-- fint the total number of orders
select 
Count(order_number) 
from gold.fact_sales

-- find total number of unique orders
select 
count(distinct order_number) 
from gold.fact_sales

-- find the total number of products 
select 
count(distinct product_name) from 
gold.dim_products

-- find the total numbr of customers
select 
count(distinct customer_number) 
from gold.dim_customers

-- find the total number of customers that has placed an order 
select 
count(distinct customer_key)
from 
gold.fact_sales


-- generate a report that shows all key metrics CALCULATED ABOVE

select 'Total Sales' as measure_name, Sum(sales_amount) measure_value from gold.fact_sales
union all
select 'Total Quantity', sum(quantity) from gold.fact_sales
union all
select 'Avg Price', avg(price) from gold.fact_sales
union all
select 'Total number of orders',count(distinct order_number) from gold.fact_sales
union all
select 'Total number of products', count(distinct product_name) from gold.dim_products 
union all
select 'Total number of customers', count(distinct customer_number) from gold.dim_customers


-- MAgnitude analysis-- where we find out aggregation by using dimension information

-- Find the total customers by country

select cntry as country,
count(customer_number) customers
from gold.dim_customers
group by cntry
ORDER BY customers desc

-- Find the total customers by gender

select 
new_gen as gender,
count(customer_number) total_customers
from gold.dim_customers
group by new_gen
order by total_customers desc

-- Find total products by category

select
category,
count(product_number) total_products
 from gold.dim_products
group by category
order by total_products desc

-- What is the average costs in each category? 

select 
category,
avg(cost) avg_cost 
 from gold.dim_products
 group by category 
 order by avg_cost desc

-- What is the total revenue generated for each category ?

select 
sum(sales_amount) sales_amount,
p.category
from gold.fact_sales s
left join gold.dim_products p
on s.product_key = p.product_key
group by p.category

-- Find the total revenue generated by each customer?

select 
c.first_name,
c.last_name,
c.customer_key,
sum(s.sales_amount) total_revenue
from gold.dim_customers c
left join gold.fact_sales s
on c.customer_key = s.customer_key
group by c.customer_key, c.first_name, c.last_name
order by total_revenue desc


-- What is the distribution of sold items across countries ?

select 
c.cntry,
sum(s.quantity) total_sold_items
from gold.dim_customers c
left join gold.fact_sales s
on c.customer_key = s.customer_key
group by c.cntry
order by total_sold_items desc


-- which 5 products generate the highest revenur


select top 5
p.product_name,
sum(sales_amount) total_revenue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key = p.product_key
group by p.product_name
order by total_revenue desc

-- which are 5 worst performin products


select top 5
p.product_name,
sum(sales_amount) total_revenue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key = p.product_key
group by p.product_name
order by total_revenue asc


-- Ranking Analysis

-- which 5 products generate highest revenue
use DataWarehouse

select top 5
p.product_name,
(s.sales_amount) total_revnue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key = p.product_key
group by product_name
order by total_revnue desc

-- which 5 products generate highest revenue using windows function


select *
from
(select 
product_name,
sum(s.sales_amount) total_revenue,
row_number() over( partition by product_name order by sum(s.sales_amount) desc) rank_products
from gold.fact_sales s
left join gold.dim_products p
on s.product_key = p.product_key
group by product_name)t

where rank_products <= 5



-- 5 worst products


select top 5
p.product_name,
sum(s.sales_amount) total_revnue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key = p.product_key
group by product_name
order by total_revnue asc


-- Advance analytics
-- Change over time analysis

  -- sleect total sales over the course of time 

  select 
  Year(order_date) order_year,
  sum(sales_amount) total_sales,
  count(distinct customer_key) as total_customers,
  SUm(quantity) as total_quanity
  from gold.fact_sales
  where order_date is not null
  group by year(order_date)
  order by year(order_date)


  select * from gold.fact_sales

  -- calculate the total sales per month
  -- and the running total of sales	over time

  select	
  order_date,
  total_sales,
  Sum(total_sales) over(order by order_date)
  from

  (select 
  --Year(order_date) order_year,
  Datetrunc(YEAR, order_date) order_date,
  sum(sales_amount) total_sales
  from gold.fact_sales
  where order_date is not null
  group by Datetrunc(YEAR, order_date)
  )t


  -- Performance nalysis

  -- analyse the yearly performance of productts bys compairing their sales yo both the average	sales performnce of the product	and the previoud year's sale 
  -- such analysis is know as year over year analysis
  with yearly_product_sales as 
  (
  select 
  year (order_date) order_year,
  product_name,
  sum(sales_amount) total_sales
  from gold.fact_sales s
  left join
  gold.dim_products p
  on s.product_key = p.product_key
  where year (order_date) is not null
  group by year (order_date) , p.product_name
  )

select
order_year,
product_name,
total_sales,
avg(total_sales) over(partition by product_name) avg_sales,
total_sales - avg(total_sales) over(partition by product_name) as diff,
case 
	when total_sales - avg(total_sales) over(partition by product_name) > 0 then 'above_avg'
	when total_sales - avg(total_sales) over(partition by product_name) < 0 then 'below_avg'
	else 'avg'
end avg_change,
Lag(total_sales) over(partition by product_name order by order_year) previous_year_sales,
total_sales - Lag(total_sales) over(partition by product_name order by order_year),
case 
	when total_sales - Lag(total_sales) over(partition by product_name order by order_year) > 0 then 'Increase'
	when total_sales - Lag(total_sales) over(partition by product_name order by order_year) > 0 then 'Decrease'
	else 'No change'
end avg_change
from yearly_product_sales
order by product_name, order_year


-- Part to whole analysis

-- which category contribute the most to overall sales

with overall_category as

(
select
category,
sum(sales_amount) total_sales
from gold.fact_sales f
left join
gold.dim_products p
on f.product_key = p.product_key
group by p.category
)

select 
category,
total_sales,
sum(total_sales) OVER(),
concat(round((cast(total_sales as float) / sum(total_sales) OVER()) * 100, 2), '%') 

from overall_category
order by total_sales desc




-- segment products into cost range and count how many products fall into each segment


select 
range,
count(product_name) 
from

(select 
product_name,
category,
cost,
case 
	when cost <= 1000 then 'low'
	when cost between 1000 and 2000 then 'medium'
 	else 'high'
end range
from gold.dim_products)t
group by range


-- group customers into 3 segments based on their spending behaviour:
-- VIP : customers atleast 12 months of history and spending more than 5000
-- Regular : Customers with at least 12 months of history but spending 5000 or less
-- NEw : customers with the lifesopan of less than	12 months 
-- and find the total number of customers by each group

with customer_spending as 
(
select 
c.customer_key,
sum(s.sales_amount) total_sales,
Min(s.order_date) first_order, 
Max(s.order_date) last_order,
datediff(month, min(order_date), max(order_date)) as lifespan
from gold.dim_customers c
left join
gold.fact_sales s
on c.customer_key = s.customer_key
group by c.customer_key
)


select
customer_segment,
count(customer_key) as total_customers
from
(
Select
customer_key,
total_sales,
lifespan,
case 
	when lifespan >= 12 and total_sales > 5000 then 'VIP'
	when lifespan >= 12 and total_sales <= 5000 then 'Regular'
	else 'New'

end customer_segment
from customer_spending
)t

group by customer_segment
order by total_customers desc


-- Build customer reports 

/*
============================================================
Customer Rport
============================================================

Purpose:
- This  report consolidates key customer metrics and behaviours

Highlights:
	1. Gathers essential fields such as names, ages, and transaction detials.
	2. Sugments customers into categories (VIP, Regular, New) and age groups.
	3. Aggregates customer-level metrics:
		- total orders
		- total sales 
		- total quantity purchased
		- total products
		- lifespan (in months )
	4. Calculates valuable KPIs:
		- recency(months since last order)
		- average order value
		- average monthly spend
===========================================================
*/

/* ---------------------------------------------------------
1) Base Query: Retrieves core columns from tables 
-----------------------------------------------------------*/

create view gold.report_customers as 

with base_query as 
(
select 
f.order_number,
f.product_key,
f.order_date,
f.sales_amount,
f.quantity,
c.customer_key,
c.customer_number,
c.first_name,
c.last_name,
CONCAT(c.first_name, ' ', c.last_name) as customer_name,
datediff(year, c.birth_date, getdate()) age ,
c.birth_date
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
where order_date is not null)

, customer_aggregation as 

(
select
customer_key,
customer_number,
customer_name,
age,
count(distinct order_number) as total_orders,
sum(sales_amount) as total_sales,
sum(quantity) as total_quantity,
count(distinct product_key) as total_products,
Max(order_date) as last_order_date,
datediff(month, min(order_date), max(order_date)) as lifespan
from base_query
group by 
	customer_key,
	customer_number,
	customer_name,
	age
	)

select
	customer_key,
	customer_number,
	customer_name,
	age,
	case when age < 20 then 'Under 20'
		when age between 20 and 29 then '20-29'
		when age between 30 and 39 then '30-39'
		when age between 40 and 49 then '40-49'
		else '50 and above'
	end as age_group,
	case 
	when lifespan >= 12 and total_sales > 5000 then 'VIP'
	when lifespan >= 12 and total_sales <= 5000 then 'Regular'
	else 'New'

	end customer_segment,
	total_orders,
	total_sales,
	total_quantity,
	total_products,
	last_order_date,
	datediff(month, last_order_date, getdate()) as recency,
	lifespan,
	-- compute avg order value
	case when total_sales = 0 then 0
		else total_sales/ total_orders 
	end as avg_order_value,
	
	-- compute avg monthly spend
	case when lifespan = 0 then total_sales
	else total_sales/lifespan
	end as avg_monthly_spend
	from customer_aggregation

	select * from gold.report_customers


	/*
	=================================================================
	Product Report
	=================================================================

	Purpose:
- This report consolidates key product metrics and behaviors.

Highlights:
1. Gathers essential fields such as product name, category, subcategory, and cost.
2. Segments products by revenue to identify High-Performers, Mid-Range, or Low-Performers.
3. Aggregates product-level metrics:
- total orders
- total sales
- total quantity sold
- total customers (unique)
- lifespan (in months)
4. Calculates valuable KPIs:
- recency (months since last sale)
- average order revenue (AOR)
- average monthly revenue

=================================================================

*/


create view gold.report_products as 
with base_query as 
(

select 
f.order_number,
f.order_date,
f.customer_key,
f.sales_amount,
f.quantity,
f.product_key,
p.product_name,
p.category,
p.subcategory,
p.cost

from gold.fact_sales f 
left join gold.dim_products p
on f.product_key = p.product_key
where order_date is not null
),

product_aggregations as (
select 
	product_key,
	product_name,
	category,
	subcategory,
	cost,
	DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS lifespan,
    MAX(order_date) AS last_sale_date,
    COUNT(DISTINCT order_number) AS total_orders,
    COUNT(DISTINCT customer_key) AS total_customers,
    SUM(sales_amount) AS total_sales,
    SUM(quantity) AS total_quantity,
    ROUND(AVG(CAST(sales_amount AS FLOAT) / NULLIF(quantity, 0)),1) AS avg_selling_price
FROM base_query

GROUP BY
	product_key,
	product_name,
	category,
	subcategory,
	cost
	)

	select
		product_key,
		product_name,
		category,
		subcategory,
		cost,
		last_sale_date,
		DATEDIFF(MONTH, last_sale_date, GETDATE()) AS recency_in_months,
		CASE
			WHEN total_sales > 50000 THEN 'High-Performer'
			WHEN total_sales >= 10000 THEN 'Mid-Range'
			ELSE 'Low-Performer'
			END AS product_segment,
		lifespan,
		total_orders,
		total_sales,
		total_quantity,
		total_customers,
		avg_selling_price,
		-- Average Order Revenue (AOR)
		CASE
			WHEN total_orders = 0 THEN 0
			ELSE total_sales / total_orders
    END AS avg_order_revenue,

    -- Average Monthly Revenue
    CASE
        WHEN lifespan = 0 THEN total_sales
        ELSE total_sales / lifespan
    END AS avg_monthly_revenue

FROM product_aggregations

select * from gold.report_products
